### ISSUE TITLE
unable to cherry-pick 54634acdd7855a808472ab064de12bd81a85c67e onto 3.30 branch

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#24000]
I am having trouble cherry-picking 54634acdd7855a808472ab064de12bd81a85c67e (from https://github.com/sourcegraph/sourcegraph/issues/23762) onto the patch release. 

When I did so (https://github.com/sourcegraph/sourcegraph/commit/e67de57082795274a7dbc99ebe8dd904f5677d4f), I got the following build errors (from https://buildkite.com/sourcegraph/sourcegraph/builds/105251#71ac62ce-7afa-4a50-b5f9-ca3e4bd676c4):

```
internal/httpcli/client.go:110:23: undefined: NewExternalHTTPClientFactory
```

I lack the context to know what needs to be done here. Could the appropriate team handle cherry-picking the appropriate commits from https://github.com/sourcegraph/sourcegraph/issues/23762 onto the `3.30` release branch: https://github.com/sourcegraph/sourcegraph/tree/3.30 ?

I have already dropped the offending commits from https://github.com/sourcegraph/sourcegraph/issues/23762 from the 3.30 branch.

**Comment by unknwon** [comment]
Cherry-picked https://github.com/sourcegraph/sourcegraph/commit/54634acdd7855a808472ab064de12bd81a85c67e into 3.30 as https://github.com/sourcegraph/sourcegraph/commit/1b777137cf2b901dccca6515bc7c439083939d85. Waiting for CI.
