### PR TITLE
symbols: Fix duplicate symbols

### PR DESCRIPTION
**Pull request by chrismwendt**
Caused by https://github.com/sourcegraph/sourcegraph/pull/20310/files?w=1#r816133824

Resolves https://github.com/sourcegraph/sourcegraph/issues/31934

Images from Camden's PR

Before: 
Screen Shot 2022-02-28 at 11 32 08

After:
Screen Shot 2022-02-28 at 11 32 33

## Test plan

Added a test.

### CODE REVIEW

**Comment by camdencheek** [comment]
lol, will close my PR

**Review by camdencheek — APPROVED** [review]
Looks great. I had this exact "pull it out into a separate function" change staged as a followup PR 😄

**Comment by chrismwendt** [comment]
We had the same exact diff 😄 https://github.com/kyoh86/exportloopref looks useful 👍
